name: Build Cross-Platform Releases

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # We build on Windows, Linux, and macOS servers
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Fix Mac Icon Size
        if: runner.os == 'macOS'
        run: sips -z 512 512 public/icon.png

      - name: Build and Publish Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
        # The `--publish always` flag tells electron-builder to upload the output
        # to the GitHub release that triggered this workflow.
        run: npm run build -- --publish always
