name: Annonce Release Discord

on:
  release:
    types: [published]

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Envoyer la notification sur Discord
        uses: sillyangel/releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "Explore Update"
          avatar: "https://github.com/Julien0ff/explore-app/blob/main/website/icon.png"
          color: "3447003" # Couleur de la barre latérale en décimal (Bleu)
